const theme = {
  font: {
    defaultFontFamily: 'Poppins_400Regular',
    defaultFontFamilyBold: 'Poppins_700Bold',
  },
  light: {
    backgroundPrimary: '#ffffff',
    backgroundInverse: '#333333',
    backgroundSecondary: '#eeeeee',
    backgroundTerciary: '#777777',
    backgroundForth: '#ffffff',
    textPrimary: '#333333',
    textSecondary: '#777777',
    textInverse: '#777777',
    primary: '#ef6c00',
    primaryText: '#ffffff',
    primaryLight: '#f3d1b5',
    secondary: '#eba469',
    terciary: '#b53d00',
    forth: '#777777',
    fifth: '#dddddd',
    sixth: '#333333',
    seventh: '#dddddd',
  },
  dark: {
    backgroundPrimary: '#333333',
    backgroundInverse: '#ffffff',
    backgroundSecondary: '#555555',
    backgroundTerciary: '#eeeeee',
    backgroundForth: '#555555',
    textPrimary: '#ffffff',
    textSecondary: '#dddddd',
    textInverse: '#eeeeee',
    primary: '#ef6c00',
    primaryText: '#ffffff',
    primaryLight: '#f3d1b5',
    secondary: '#eba469',
    terciary: '#b53d00',
    forth: '#777777',
    fifth: '#dddddd',
    sixth: '#333333',
    seventh: '#555555',
  },
};

export default theme;
