import React, { Component } from 'react';
import { View, Text, Image, TouchableHighlight, StatusBar, AsyncStorage } from 'react-native';
import { Container, Header, Right, H1, H2, H3, Left, Body, Title, Content, Button, Icon } from 'native-base';

import PushNotification from 'react-native-push-notification';

import form from '../theme/form';
import general from '../theme/general';

export default class Notification extends Component {

    constructor(props) {
        super(props);
    }

    goBack() {
        this.props.navigator.pop();
    }

    test() {
        PushNotification.configure({
            onNotification: function(notification) {
                console.log( 'NOTIFICATION:', notification );
            },
            senderID: '',
            popInitialNotification: true,
            requestPermissions: true,
        });

        PushNotification.localNotificationSchedule({
            message: "Seu lembrete para ler a bíblia está aqui.",
            date: new Date(Date.now() + (3 * 1000)),
            // repeatType: 'day'
        });
    }

    test1() {
        PushNotification.localNotification({
            /* Android Only Properties */
            id: '0', // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: "My Notification Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "My big text that will be shown when notification is expanded", // (optional) default: "message" prop
            subText: "This is a subText", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification

            /* iOS and Android properties */
            title: "My Notification Title", // (optional, for iOS this is only used in apple watch, the title will be the app name on other iOS devices)
            message: "My Notification Message", // (required)
            playSound: false, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            number: '10', // (optional) Valid 32 bit integer specified as string. default: none (Cannot be zero)
            repeatType: 'day', // (Android only) Repeating interval. Could be one of `week`, `day`, `hour`, `minute, `time`. If specified as time, it should be accompanied by one more parameter 'repeatTime` which should the number of milliseconds between each interval
            actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
        });
    }

    render() {

        return (
            <Container style={{flex: 1}} backgroundColor="#555">
                <Header noShadow={true} transparent style={{backgroundColor: '#444'}}>
                    <Left>
                        <Button transparent onPress={() => this.goBack()}>
                            <Icon name='ios-arrow-back' style={{color: '#fff'}}/>
                        </Button>
                    </Left>
                    <Body>
                        <Title style={{color: '#fff'}}>Leitura diária</Title>
                    </Body>
                    <Right></Right>
                </Header>

                <Content style={general.content}>

                    <Button>
                        <Text onPress={() => this.test()}>Notificação</Text>
                    </Button>

                </Content>

                <StatusBar backgroundColor="#444" barStyle="light-content" />

            </Container>
        );
    }
}
